presubmits:
  hemanik/prow-test:
  - name: unit-tests         # Names need not be unique.
    always_run: true         # Run for every PR, or only when requested.
    skip_report: false       # Whether to skip setting a status on GitHub.
    context: unit-tests      # Status context. Usually the job name.
    max_concurrency: 10      # Run no more than this number concurrently.
    agent: kubernetes        
    spec:                    # Valid Kubernetes PodSpec. 
      containers:
      - image: alpine
        command:
        - printenv
    trigger: "(?m)^/test this"
    rerun_command: "/test this"
    